### ISSUE TITLE
Review the spot request type

### ISSUE THREAD

**Issue by huogerac** [spacetimelabs/new_resources#2]
It seems the spot request type is 'persistent' which makes the instance keeps alive forever even if you terminate it.
- At least add this behavior to the documentation.
- Check the one-time spot request out
- Recommend to use the terraform destroy instead

**Comment by ecarrara** [comment]
I don't know why TerraForm uses `persistent` as default, but [they make this clear in the first paragraph of `aws_spot_instance` documentation](https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html):

> By default Terraform creates Spot Instance Requests with a persistent type, which means that for the duration of their lifetime, AWS will launch an instance with the configured details if and when the spot market will accept the requested price.

![Spot Lifecycle](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/images/spot_lifecycle.png)

 I think that for most of our use cases `one-time` spot request makes more sense! Other tools, like [Ansible, uses `one-time` as default](https://docs.ansible.com/ansible/latest/modules/ec2_module.html#parameter-spot_type).
